facturacion/apps/principal/urls.py
from django.conf.urls import patterns, url
from .views import *

urlpatterns = patterns('facturacion.apps.principal.views',
	url(r'^$', 'home', name = 'home'),
	url(r'^list-product/$', 'list_product', name = 'list_product'),
	url(r'^find-product/$', 'find_product', name = 'find_product'),
	url(r'^save-factura/$', 'factura', name = 'factura'),
	url(r'^list-factura/$', 'list_factura', name = 'list_factura'),
	url(r'^delete-factura/(?P<factura_pk>\d+)/$', 'delete_factura', name = 'delete_factura'),
	url(r'^detail-factura/(?P<factura_pk>\d+)/$', 'detail_factura', name = 'detail_factura'),
	url(r'^add-product/(?:/(?P<product_pk>\d+))?', 'add_product', name = 'add_product'),
	url(r'^delete-product/(?P<product_pk>\d+)/$', 'delete_product', name = 'delete_product'),
	url(r'^factura-print/(?P<factura_pk>\d+)/$', FacturaPDFView.as_view(), name = 'pdf_factura'),
)

facturacion/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^admin/', include(admin.site.urls)),
	url(r'^', include('facturacion.apps.principal.urls')),
]

facturacion/apps/principal/models.py
# -*- coding: utf-8 -*-
from django.db import models

class Producto(models.Model):
	name = models.CharField(max_length = 50)
	price = models. DecimalField(max_digits = 11, decimal_places = 2)

	def __str__(self):
		return self.name

	def __unicode__(self):
		return self.name

class Factura(models.Model):
	code = models.CharField(max_length = 10, blank = True, null = True)
	date = models.DateField(auto_now = False)

	def __str__(self):
		return self.code

class DetalleFactura(models.Model):
	producto = models.ForeignKey(Producto)
	factura = models.ForeignKey(Factura)
	cantidad = models.IntegerField()

facturacion/apps/principal/forms.py
from django.forms import *
from django import forms
from .models import *

class ProductForm(forms.ModelForm):
	class Meta:
		model = Producto
		fields = '__all__'
		widgets = {
			'name': TextInput(attrs = {'class': 'form-control', 'maxlength': '50', 'required': True}),
			'price': TextInput(attrs = {'class': 'form-control number-val', 'required': True})
		}
		labels = {
			'name': 'Nombre del producto',
			'price': 'Precio del producto'
		}

facturacion/apps/principal/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponseRedirect, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from easy_pdf.views import PDFTemplateView
from django.shortcuts import render
from .models import *
import datetime, json
from .forms import *

def home(request):
	return render(request, 'home.html', {'title': 'Bienvenido'})

def list_product(request):
	products = Producto.objects.all()
	return render(request, 'list_product.html', {'title': 'Lista de Productos', 'products': products})

def find_product(request):
	results = []
	response = {}
	if request.is_ajax:
		word = request.GET.get('term','')
		products = Producto.objects.filter(name__icontains = word)
		if products:
			for product in products:
				response['pk'] = product.pk
				response['name'] = product.name
				response['label'] = product.name
				response['price'] = str(int(product.price))
				results.append(response)
		else:
			response['label'] = "No hay resultados"
			results.append(response)
		data_json = json.dumps(results)
	else:
		data_json = 'fail'
	mimetype = "application/json"
	return HttpResponse(data_json, mimetype)

def add_product(request, product_pk):
	response = {}
	response['edit'] = request.GET.get('new')
	try:
		producto = Producto.objects.get(pk = product_pk)
		product = producto.pk
		response['edit'] = 'true'
	except Producto.DoesNotExist:
		producto = product_pk
		product = producto
	if request.method == 'POST':
		form = ProductForm(request.POST, instance = producto)
		if form.is_valid():
			product_data = form.save()
			response['pk'] = product_data.pk
			response['name'] = product_data.name
			response['price'] = str(product_data.price)
			response['type'] = "success"
			response['response'] = "Operacion realizada con exito"
		else:
			response['response'] = "Ha ocurrido un error"
			response['type'] = "error"
		return HttpResponse(json.dumps(response), content_type = 'application/json')
	else:
		form = ProductForm(instance = producto)
	return render(request, 'form-producto.html', {'title': 'Nuevo Producto', 'product_val': product, 'new': request.GET.get('new'),'forms': form})

def delete_product(request, product_pk):
	response = {}
	try:
		producto = Producto.objects.get(pk = product_pk)
		producto.delete()
		response['type'] = 'success'
		response['msg'] = 'Producto eliminado'
	except Producto.DoesNotExist:
		response['type'] = 'error'
		response['msg'] = 'Producto no encontrado'
	return HttpResponse(json.dumps(response), "application/json")

@csrf_exempt
def factura(request):
	response = {}
	if request.method == 'POST':
		data = request.POST
		date_now = datetime.datetime.now()
		code = 'AAA'+date_now.strftime("%y")+str(date_now.day)+str(date_now.minute)+str(date_now.second)
		factura = Factura(code = code, date = date_now)
		factura.save()
		for key, value in data.iteritems():
			product = Producto.objects.get(pk = key)
			detalle_factura = DetalleFactura(producto = product, factura = factura, cantidad = value)
			detalle_factura.save()
		print code
		response['response'] = True
		response['message'] = factura.pk
	else:
		response['response'] = False
		response['message'] = 'Ha ocurrido un error'
	return HttpResponse(json.dumps(response), "application/json")

def list_factura(request):
	facturas = Factura.objects.all()
	return render(request, 'list_factura.html', {'title': 'Lista de Facturas', 'facturas': facturas})

def detail_factura(request, factura_pk):
	factura = Factura.objects.get(pk = factura_pk)
	return render(request, 'detail-factura.html', {'title': 'Detalle de '+factura.code, 'factura': factura})

def delete_factura(request, factura_pk):
	response = {}
	try:
		factura = Factura.objects.get(pk = factura_pk)
		factura.delete()
		response['type'] = 'success'
		response['msg'] = 'Factura eliminada'
	except Factura.DoesNotExist:
		response['type'] = 'error'
		response['msg'] = 'Factura no encontrada'
	return HttpResponse(json.dumps(response), "application/json")

class FacturaPDFView(PDFTemplateView):
	template_name = "pdf_factura.html"

	def get_context_data(self, **kwargs):
		context = super(FacturaPDFView, self).get_context_data(**kwargs)
		factura = Factura.objects.get(pk = self.kwargs['factura_pk'])
		context['title'] = factura.code
		context['query'] = factura
		return context

facturacion/apps/principal/templates/detail-factura.html
{% load humanize %}

{% load custom_filters %}

<div class="modal-dialog" role="document">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myModalLabel">{{ title }}</h4>
		</div>
		<div class="modal-body">
			<table class="table table-striped table-bordered">
				<thead>
					<tr>
						<th>Nombre</th>
						<th>Cantidad</th>
						<th>Precio Unitario</th>
						<th>Precio Total</th>
					</tr>
				</thead>
				<tbody>
					{% for fact in factura.detallefactura_set.all %}
						<tr>
							<td>{{ fact.producto.name }}</td>
							<td>{{ fact.cantidad }}</td>
							<td>$ {{ fact.producto.price|floatformat|intcomma }}</td>
							<td>$ {% multiply fact.cantidad fact.producto.price %}</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
		<div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
		</div>
	</div>
</div>

facturacion/apps/principal/templates/elements/menu.html
<div class="navbar navbar-default navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<a href="{% url 'home' %}" class="navbar-brand">Facturación</a>
			<button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
		</div>
		<div class="navbar-collapse collapse" id="navbar-main">
			<ul class="nav navbar-nav navbar-right">
				<li><a href="{% url 'home' %}">Inicio</a></li>
				<li><a href="{% url 'list_product' %}">Productos</a></li>
				<li><a href="{% url 'list_factura' %}">Facturas</a></li>
			</ul>
		</div>
	</div>
</div>

facturacion/apps/principal/templates/form-producto.html
<div class="modal-dialog" role="document">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myModalLabel">{{ title }}</h4>
		</div>
		<form action="{% url 'add_product' product_val %}?new={{ new }}" method="POST">
			{% csrf_token %}
			<div class="modal-body">
				<div class="row">
					{% for form in forms %}
						<div class="col-md-12">
							<div class="form-group">
								<label>{{ form.label }}</label>
								{{ form }}
							</div>
						</div>
					{% endfor %}
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
				<input type="submit" value="Guardar" class="btn btn-success"/>
			</div>
		</form>
	</div>
</div>

<script>
	$(function() {
		$('.form-group').on('keydown', '.number-val', function(e){-1!==$.inArray(e.keyCode,[46,8,9,27,13,110,190])||/65|67|86|88/.test(e.keyCode)&&(!0===e.ctrlKey||!0===e.metaKey)||35<=e.keyCode&&40>=e.keyCode||(e.shiftKey||48>e.keyCode||57<e.keyCode)&&(96>e.keyCode||105<e.keyCode)&&e.preventDefault()});
	})
	$("form").submit(function(event){
		event.preventDefault();
		var formData = new FormData(this);
		$.ajax({
			url: $(this).attr('action'),
			type: $(this).attr('method'),
			dataType: "json",
			data: formData,
			cache: false,
			contentType: false,
			processData: false,
			success: function(data){
				console.log(data);
				$('.product-'+data.pk).remove();
				if(data.edit != 'true'){
					$('.table tbody').append(
						"<tr class='product-"+data.pk+"' val="+data.pk+">"+
							"<td>"+data.name+"</td>"+
							'<td>'+
								"<a href='#' class='btn btn-default minus' val='"+data.pk+"'>"+
									"<i class='glyphicon glyphicon-minus'></i>"+
								"</a>"+
								"<input type='text' class='form-control quant-"+data.pk+"' style='width: 50px; display: inline;' value='1'>"+
								"<a href='#'' class='btn btn-default plus' val='"+data.pk+"'>"+
									"<i class='glyphicon glyphicon-plus'></i>"+
								"</a>"+
							"</td>"+
							"<td>$ "+Number(data.price).toLocaleString('en')+"</td>"+
							"<td class='price-tot-"+data.pk+"' val='"+data.price+"'>"+format(data.price)+"</td>"+
							"<td>"+
								"<a href='#' class='btn btn-danger remove' val='"+data.pk+"'>"+
									"<i class='glyphicon glyphicon-remove'></i>"+
								"</a>"+
							"</td>"+
						"</tr>"
					);
				}else{
					$('.table tbody').append(
						"<tr class='product-"+data.pk+"'>"+
							"<td>"+data.name+"</td>"+
							"<td>$ "+Number(data.price).toLocaleString('en')+"</td>"+
							"<td>"+
								"<a href='/delete-product/"+data.pk+"/' class='delete btn btn-danger' id='"+data.pk+"'>Eliminar</a> <a href='/add-product//"+data.pk+"' class='open-modal btn btn-success' data-toggle='modal' data-target='#Modal'>Editar</a>"+
							"</td>"+
						"</tr>"
					);
					send_alert(data.type, data.response);
				}
				$('#Modal').modal('hide');
			}
		});
	});
</script>

facturacion/apps/principal/templates/home.html
{% extends 'layout/base.html' %}

{% block content %}
	{% include 'elements/menu.html' %}
	<div class="container">
		<div class="row">
			<div class="page-header">
				<div class="row">
					<h1>
						Agrega elementos a la factura
						<a href="{% url 'add_product' %}" class="btn btn-success open-modal" data-toggle="modal" data-target="#Modal">Nuevo producto</a>
					</h1>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="form-group">
					<label class="control-label">Buscar producto</label>
					<input type="text" class="form-control" id="find-product" name="find-product">
				</div>
			</div>
			<div class="col-md-12">
				<table class="table table-striped table-hover">
					<thead>
						<tr>
							<th>Nombre</th>
							<th>Cantidad</th>
							<th>Precio unitario</th>
							<th>Precio total</th>
							<th></th>
						</tr>
					</thead>
					<tbody></tbody>
				</table>
				<div class="text-center">
					<a href="#" class="btn btn-success print">Imprimir Factura</a>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

{% block content_script %}
	$('html').on('click', '.print', function(event){
		event.preventDefault();
		var data_product = {}
		$('table tbody tr').each(function(i, el) {
			pk = $(el).attr('val');
			data_product[pk] = $('.quant-'+pk).val();
		});
		if(Object.keys(data_product) == 0){
			send_alert('error', 'No hay productos');
		}else{
			$.ajax({
				url: "{% url 'factura' %}",
				type: "POST",
				dataType: "json",
				data: data_product,
				success: function(data){
					if(data.response == true){
						Lobibox.window({
							title: "Factura No. "+data.message,
							height: 110,
							baseClass: 'animated-super-fast text-center',
							content: "<a href='/factura-print/"+data.message+"' target='_blank' class='btn btn-success text-center'>Imprimir</a>"
						});
						$("tbody").empty();
					}else{
						alert(data.message);
					}
				}
			});
		}
	});
	$('table').on('click', '.plus', function(event){
		event.preventDefault();
		pk = $(this).attr('val');
		sum = parseInt($('.quant-'+pk).val()) + 1;
		put_value(pk, sum);
	});
	$('table').on('click', '.minus', function(event){
		event.preventDefault();
		pk = $(this).attr('val');
		sum = parseInt($('.quant-'+pk).val()) - 1;
		if(sum == 0){
			alert("Valor mínimo debe ser 1");
		}else{
			put_value(pk, sum);
		}
	});
	$('table').on('click', '.remove', function(event){
		event.preventDefault();
		pk = $(this).attr('val');
		$('.product-'+pk).remove();
	});
	function put_value(pk, sum){
		$('.quant-'+pk).val(sum);
		price = parseInt($('.price-tot-'+pk).attr('val')) * sum;
		$('.price-tot-'+pk).empty();
		$('.price-tot-'+pk).html(format(price));
	}
	function add_element(pk, name, price){
		$('.table tbody').append(
			'<tr class="product-'+pk+'" val="'+pk+'">'+
				'<td>'+name+'</td>'+
				'<td>'+
					'<a href="#" class="btn btn-default minus" val="'+pk+'">'+
						'<i class="glyphicon glyphicon-minus"></i>'+
					'</a>'+
					'<input type="text" class="form-control quant-'+pk+'" style="width: 50px; display: inline;" value="1">'+
					'<a href="#" class="btn btn-default plus" val="'+pk+'">'+
						'<i class="glyphicon glyphicon-plus"></i>'+
					'</a>'+
				'</td>'+
				'<td>'+format(price)+'</td>'+
				'<td class="price-tot-'+pk+'" val="'+price+'">'+format(price)+'</td>'+
				'<td>'+
					'<a href="#" class="btn btn-danger remove" val="'+pk+'">'+
						'<i class="glyphicon glyphicon-remove"></i>'+
					'</a>'+
				'</td>'+
			'</tr>'
		);
	}
	$("#find-product").autocomplete({
		minLength: 1,
		source: "{% url 'find_product' %}",
		select: function(event, ui){
			if($('.product-'+ui.item.pk).length){
				send_alert('info', 'Articulo ya agregado');
			}else{
				add_element(ui.item.pk, ui.item.name, ui.item.price);
			}
			$(this).val('');
			return false;
		}
	});
{% endblock content_script %}

facturacion/apps/principal/templates/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Facturación :: {{ title }}</title>
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/lobibox.css' %}">
	<script src="{% static 'js/jquery.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/standard.js' %}"></script>
	<script src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script src="{% static 'js/lobibox.js' %}"></script>
	{% block content_head %}{% endblock content_head %}
</head>
<body>
	{% block content %}{% endblock content %}
	<div class="modal fade" id="Modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"></div>
	<script>
		{% block content_script %}
		{% endblock content_script %}
	</script>
</body>
</html>

facturacion/apps/principal/templates/list_factura.html
{% extends 'layout/base.html' %}

{% load static %}

{% block content_head %}
	<link rel="stylesheet" href="{% static 'css/jquery.dataTables.min.css' %}">
	<script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
{% endblock content_head %}

{% block content %}
	{% include 'elements/menu.html' %}
	<div class="container">
		<div class="row">
			<div class="page-header">
				<div class="row">
					<h1>
						{{ title }}
					</h1>
				</div>
			</div>
		</div>
		<div class="row">
			<table id="list-factura" class="table table-striped table-bordered">
				<thead>
					<tr>
						<th>Código</th>
						<th>Fecha</th>
						<th>Acción</th>
					</tr>
				</thead>
				<tbody>
					{% for factura in facturas %}
					<tr class="factura-{{ factura.pk }}">
						<td>{{ factura.code }}</td>
						<td>{{ factura.date }}</td>
						<td>
							<a href="{% url 'delete_factura' factura.pk %}" class="delete btn btn-danger" id="{{ factura.pk }}">Eliminar</a>
							<a href="{% url 'detail_factura' factura.pk %}" class="btn btn-primary open-modal" data-toggle="modal" data-target="#Modal">Detalle</a>
							<a href="{% url 'pdf_factura' factura.pk %}" target='_blank' class='btn btn-success text-center'>Imprimir</a>
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
{% endblock content %}

{% block content_script %}
	$(document).on("click", ".delete", function(e){
		var id = $(this).attr('id');
		var url = $(this).attr('href');
		Lobibox.alert('info', {
			title: "Información",
			msg: "¿Desea eliminar la factura?",
			buttons:{
				yes: {
					'class': 'btn btn-warning'
				},
				no: {
					'class': 'btn btn-primary'
				}
			},
			callback: function(lobibox, type){
				if(type == 'yes'){
					$.get(url, function(response){
						send_alert(response.type, response.msg);
					}).done(function(){
						$('.factura-'+id).remove();
					});
				}
				else{
					send_alert('success', 'Cancelado por el usuario');
				}
			}
		});
		return false;
	});
	$('#list-factura').DataTable();
{% endblock content_script %}

facturacion/apps/principal/templates/list_product.html
{% extends 'layout/base.html' %}

{% load static %}

{% load humanize %}

{% block content_head %}
	<link rel="stylesheet" href="{% static 'css/jquery.dataTables.min.css' %}">
	<script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
{% endblock content_head %}

{% block content %}
	{% include 'elements/menu.html' %}
	<div class="container">
		<div class="row">
			<div class="page-header">
				<div class="row">
					<h1>
						{{ title }}
						<a href="{% url 'add_product' %}?new=true" class="btn btn-success open-modal" data-toggle="modal" data-target="#Modal">Nuevo producto</a>
					</h1>
				</div>
			</div>
		</div>
		<div class="row">
			<table id="list-product" class="table table-striped table-bordered">
				<thead>
					<tr>
						<th>Nombre</th>
						<th>Precio</th>
						<th>Acción</th>
					</tr>
				</thead>
				<tbody>
					{% for product in products %}
					<tr class="product-{{ product.pk }}">
						<td>{{ product.name }}</td>
						<td>$ {{ product.price|floatformat|intcomma }}</td>
						<td>
							<a href="{% url 'delete_product' product.pk %}" class="delete btn btn-danger" id="{{ product.pk }}">Eliminar</a>
							<a href="{% url 'add_product' product.pk %}" class="open-modal btn btn-success" data-toggle="modal" data-target="#Modal">Editar</a>
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
{% endblock content %}

{% block content_script %}
	$(document).on("click", ".delete", function(e){
		var id = $(this).attr('id');
		var url = $(this).attr('href');
		Lobibox.alert('info', {
			title: "Información",
			msg: "¿Desea eliminar el producto?. Se eliminará también todas las facturas realizadas con el producto a eliminar",
			buttons:{
				yes: {
					'class': 'btn btn-warning'
				},
				no: {
					'class': 'btn btn-primary'
				}
			},
			callback: function(lobibox, type){
				if(type == 'yes'){
					$.get(url, function(response){
						send_alert(response.type, response.msg);
					}).done(function(){
						$('.product-'+id).remove();
					});
				}
				else{
					send_alert('success', 'Cancelado por el usuario');
				}
			}
		});
		return false;
	});
	$('#list-product').DataTable();
{% endblock content_script %}

facturacion/apps/principal/templates/pdf_factura.html
{% load humanize %}

{% load custom_filters %}

<html>
	<head>
		<title>{{ title }}</title>
		<style type="text/css">
			@page {
				size: 8cm x {% height query.detallefactura_set.all.count %}cm;
				margin: 0.5cm;
				@frame footer {
					-pdf-frame-content: footerContent;
					bottom: 0cm;
					height: 1cm;
				}
			}
			body {
				text-align: center;
				font-size: 10.5px;
				font-family: 'Courier Bold';
			}
			table {
				border-collapse: collapse;
			}
			td, th {
				padding: 1px 0px;
			}
		</style>
	</head>
	<body>
		<table>
			<thead>
				<tr>
					<th>VARIEDADES ABNEL</th>
				</tr>
				<tr>
					<th>NIT: 39575578-1</th>
				</tr>
				<tr>
					<th>EMAIL: VARIEDADESAAA@GMAIL.COM</th>
				</tr>
				<tr>
					<th>Mz B. C# 34 B/SOLARIS.</th>
				</tr>
				<tr>
					<th>GIRARDOT - CUNDINAMARCA</th>
				</tr>
				<tr>
					<th>TIQUETE DE VENTA No. {{ title }}</th>
				</tr>
				<tr>
					<th>FECHA: {{ query.date }}</th>
				</tr>
				<tr>
					<th>REGIMEN SIMPLIFICADO</th>
				</tr>
			</thead>
		</table>
		<table>
			<tbody>
				<tr>
					<td colspan="4">-----------------------------------------------------------------------------</td>
				</tr>
				<tr style="text-align:center">
					<td style="width: 200px">DESCRIPCION</td>
					<td style="width: 80px">CANT.</td>
					<td>VR. UNITARIO</td>
					<td>VR. TOTAL</td>
				</tr>
				<tr>
					<td colspan="4">-----------------------------------------------------------------------------</td>
				</tr>
				{% for detalle in query.detallefactura_set.all %}
					<tr style="text-align:center">
						<td style="text-align:left">{{ detalle.producto.name }}</td>
						<td>{{ detalle.cantidad }}</td>
						<td>$ {{ detalle.producto.price|floatformat|intcomma }}</td>
						<td>$ {% multiply detalle.cantidad detalle.producto.price %}</td>
					</tr>
				{% endfor %}
				<tr>
					<td colspan="4">-----------------------------------------------------------------------------</td>
				</tr>
				<tr>
					<th colspan="3">TOTAL</th>
					<th>$ {% multiply_tot query.code %}</th>
				</tr>
			</tbody>
		</table>
	</body>
</html>